name: Build ALL images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
        - aphid
        - chrysididae
        - cockroach
        - coleorrhyncha
        - coreoidea
        - dermaptera
        - embioptera
        - grylloblattodea
        - lygaeoidea
        - mantodea
        - mantophasmatodea
        - orthoptera
        - phasmida
        - plecoptera
        - psocodea
        - zoraptera 

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    
    - name: Build image
      run: ./build_image.sh ${{ env.REGISTRY }}/sfg-taxonpages/${{ matrix.repo }}

    - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image to registry
      run: docker push ${{ env.REGISTRY }}/sfg-taxonpages/${{ matrix.repo }}
